#!/usr/bin/env bash

set -e

VERSION='1.0.0'
GROUP='laplacian-core'

PROJECT_BASE_DIR=$(cd $"${BASH_SOURCE%/*}/../" && pwd)
SUBPROJECTS_DIR="$PROJECT_BASE_DIR/subprojects"

DIST_DIR="$PROJECT_BASE_DIR/dist"

METAMODEL_MODEL_MODULE_NAME="metamodel-model"
METAMODEL_MODEL_DIR="$SUBPROJECTS_DIR/$METAMODEL_MODEL_MODULE_NAME"
METAMODEL_MODEL_MODULE_PATH="$DIST_DIR/$GROUP.$METAMODEL_MODEL_MODULE_NAME-$VERSION.zip"


ENTITY_PLUGIN_TEMPLATE_MODULE_NAME="entity-plugin-template"
ENTITY_PLUGIN_TEMPLATE_DIR="$SUBPROJECTS_DIR/$ENTITY_PLUGIN_TEMPLATE_MODULE_NAME"
ENTITY_PLUGIN_TEMPLATE_MODULE_PATH="$DIST_DIR/$GROUP.$ENTITY_PLUGIN_TEMPLATE_MODULE_NAME-$VERSION.zip"


METAMODEL_ENTITY_PLUGIN_MODULE_NAME="metamodel-entity-plugin"
METAMODEL_ENTITY_PLUGIN_DIR="$SUBPROJECTS_DIR/$METAMODEL_ENTITY_PLUGIN_MODULE_NAME"
METAMODEL_ENTITY_PLUGIN_PATH="$DIST_DIR/$GROUP.$METAMODEL_ENTITY_PLUGIN_MODULE_NAME-$VERSION.jar"
METAMODEL_ENTITY_PLUGIN_BUILT_MODULE="$METAMODEL_ENTITY_PLUGIN_DIR/build/libs/$GROUP.$METAMODEL_ENTITY_PLUGIN_MODULE_NAME-$VERSION.jar"

GRADLE="./gradlew"
ZIP="jar -cfM"

main() {
  set -x
  generate_metamodel_entity_plugin_src || die
  build_metamodel_entity_plugin || die
  update_distribution || die
}

die() {
  echo "$0 FAILED!!" 1>&2
  exit 1
}

generate_metamodel_entity_plugin_src() {
  rm -rf $METAMODEL_ENTITY_PLUGIN_DIR \
  && \
  laplacian generate \
    --template $ENTITY_PLUGIN_TEMPLATE_DIR \
    --model $METAMODEL_MODEL_DIR \
    --plugin $METAMODEL_ENTITY_PLUGIN_PATH \
    --destination $METAMODEL_ENTITY_PLUGIN_DIR
}

build_metamodel_entity_plugin() {
  (cd $METAMODEL_ENTITY_PLUGIN_DIR
    $GRADLE build
  )
}

update_distribution() {
  cp -f $METAMODEL_ENTITY_PLUGIN_BUILT_MODULE $METAMODEL_ENTITY_PLUGIN_PATH \
  && \
  (cd $METAMODEL_MODEL_DIR
    $ZIP $METAMODEL_MODEL_MODULE_PATH .
  ) \
  && \
  (cd $ENTITY_PLUGIN_TEMPLATE_DIR
    $ZIP $ENTITY_PLUGIN_TEMPLATE_MODULE_PATH .
  )
}

main
